name: Windows Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # If a spec file was ever committed, it overrides CLI flags. Remove it.
      - name: Remove pinned spec if present
        shell: cmd
        run: |
          if exist BeirutPOS.spec del /f /q BeirutPOS.spec

      - name: PyInstaller one-dir build (icon/assets optional)
        shell: cmd
        run: |
          set ICON=
          if exist assets\app.ico set ICON=--icon assets\app.ico

          set DATAS=
          if exist assets set DATAS=--add-data "assets;assets"

          py -m PyInstaller --noconsole --name "BeirutPOS" ^
            --hidden-import PyQt6.QtPrintSupport ^
            --collect-submodules PyQt6 ^
            %ICON% %DATAS% beirut_pos\__main__.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BeirutPOS-windows
          path: dist/BeirutPOS/**
          if-no-files-found: error
