name: Build (Windows)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  win-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # You can keep 3.13.x; PyInstaller supports it.
          python-version: '3.13'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyinstaller-hooks-contrib pyqt6

      - name: Prepare ICON env var (optional)
        shell: pwsh
        run: |
          $iconPath = "assets/app.ico"   # adjust if your .ico path differs
          if (Test-Path $iconPath) { $env:ICON = $iconPath } else { $env:ICON = "" }
          "ICON=$($env:ICON)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          $args = @(
            "beirut_pos/__main__.py",      # <-- change to your entry point
            "--name","BeirutPOS",          # output exe name
            "--onefile",
            "--noconsole",
            "--clean"
          )
          if ($env:ICON) { $args += @("--icon",$env:ICON) }
          python -m PyInstaller @args

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BeirutPOS-win
          path: dist/BeirutPOS.exe
