name: Build (Windows)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  win-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller pyinstaller-hooks-contrib PyQt6

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          $args = @(
            "beirut_pos/__main__.py",
            "--name","BeirutPOS",
            "--onefile",
            "--noconsole",
            "--clean",
            "--add-data","assets;assets"
          )
          if (Test-Path "assets/app.ico") { $args += @("--icon","assets/app.ico") }
          python -m PyInstaller @args

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BeirutPOS-win
          path: dist/BeirutPOS.exe

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/BeirutPOS.exe
